/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StakeRouteImport } from './routes/stake'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AssetSymbolRouteImport } from './routes/asset.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeRoute = StakeRouteImport.update({
  id: '/stake',
  path: '/stake',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AssetSymbolRoute = AssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/learn': typeof LearnRoute
  '/orders': typeof OrdersRoute
  '/plan': typeof PlanRoute
  '/pools': typeof PoolsRoute
  '/profile': typeof ProfileRoute
  '/stake': typeof StakeRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/watch': typeof WatchRoute
  '/admin/login': typeof AdminLoginRoute
  '/asset/$symbol': typeof AssetSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/learn': typeof LearnRoute
  '/orders': typeof OrdersRoute
  '/plan': typeof PlanRoute
  '/pools': typeof PoolsRoute
  '/profile': typeof ProfileRoute
  '/stake': typeof StakeRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/watch': typeof WatchRoute
  '/admin/login': typeof AdminLoginRoute
  '/asset/$symbol': typeof AssetSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/learn': typeof LearnRoute
  '/orders': typeof OrdersRoute
  '/plan': typeof PlanRoute
  '/pools': typeof PoolsRoute
  '/profile': typeof ProfileRoute
  '/stake': typeof StakeRoute
  '/terms': typeof TermsRoute
  '/trade': typeof TradeRoute
  '/watch': typeof WatchRoute
  '/admin/login': typeof AdminLoginRoute
  '/asset/$symbol': typeof AssetSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/learn'
    | '/orders'
    | '/plan'
    | '/pools'
    | '/profile'
    | '/stake'
    | '/terms'
    | '/trade'
    | '/watch'
    | '/admin/login'
    | '/asset/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/book'
    | '/learn'
    | '/orders'
    | '/plan'
    | '/pools'
    | '/profile'
    | '/stake'
    | '/terms'
    | '/trade'
    | '/watch'
    | '/admin/login'
    | '/asset/$symbol'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/learn'
    | '/orders'
    | '/plan'
    | '/pools'
    | '/profile'
    | '/stake'
    | '/terms'
    | '/trade'
    | '/watch'
    | '/admin/login'
    | '/asset/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  LearnRoute: typeof LearnRoute
  OrdersRoute: typeof OrdersRoute
  PlanRoute: typeof PlanRoute
  PoolsRoute: typeof PoolsRoute
  ProfileRoute: typeof ProfileRoute
  StakeRoute: typeof StakeRoute
  TermsRoute: typeof TermsRoute
  TradeRoute: typeof TradeRoute
  WatchRoute: typeof WatchRoute
  AssetSymbolRoute: typeof AssetSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stake': {
      id: '/stake'
      path: '/stake'
      fullPath: '/stake'
      preLoaderRoute: typeof StakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/asset/$symbol': {
      id: '/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  LearnRoute: LearnRoute,
  OrdersRoute: OrdersRoute,
  PlanRoute: PlanRoute,
  PoolsRoute: PoolsRoute,
  ProfileRoute: ProfileRoute,
  StakeRoute: StakeRoute,
  TermsRoute: TermsRoute,
  TradeRoute: TradeRoute,
  WatchRoute: WatchRoute,
  AssetSymbolRoute: AssetSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
